sudo: required
language: ruby
rvm:
  - 2.2.1
cache: bundler

services:
  - docker

script: >
  DATABASE_URL=postgres://localhost/celebrasy-ci
  HEADLESS=true
  RACK_ENV=test
  bin/rake db:create db:migrate test

after_success:
  - bin/deploy/com/build
  - bin/deploy/com/publish

addons:
  code_climate:
    repo_token: 97d1ac04ffd9a627187c971bd18d9e4367da327ac5512fb3b835234bf57ffbf1
