language: ruby
cache: bundler
rvm:
  - 2.2.1
before_script:
  - RAILS_ENV=test bundle exec rake db:create db:migrate
script:
  - bundle exec bin/rspec
  - HEADLESS=true bundle exec bin/cucumber
addons:
  code_climate:
    repo_token: 55e8a3c1e30ba0213a00213a
