default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: celebrasy_development
  url: <%= ENV["DATABASE_URL"] %>

test: &test
  <<: *default
  database: celebrasy_test
  url: <%= ENV["DATABASE_URL"] %>

production:
  <<: *default

cucumber:
  <<: *test
