default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

test: &test
  <<: *default
  database: celebrasy_test

development:
  <<: *default
  database: celebrasy_development

cucumber:
  <<: *test

production:
  database: celebrasy_production
  host: dockerpg
  username: postgres
  password:
