default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: celebrasy_development

test: &test
  <<: *default
  database: celebrasy_test

production:
  <<: *default
  database: celebrasy_production
  #username: celebrasy
  #password: <%= ENV['CELEBRASY_DATABASE_PASSWORD'] %>

cucumber:
  <<: *test
